fix(tonemapping): ACT-956 tonemapping fix
readyplayerme/visage pull request #91
Opened 2024-09-10 15:16 UTC by Jarvv

Changes:
- Reduced default back light intensity from 8->3
- Moved back light slightly forward to reduce harsh outlines when rotating avatar
- Renabled tone mapping on materials with an emissive map
- Fixed attachment meshes not being parented correctly on fallback

Old:
![Screenshot 2024-09-10 at 16 04 57](https://github.com/user-attachments/assets/b4eb100c-3971-4546-991e-dd9d4a0b5382)

New:
![Screenshot 2024-09-10 at 16 04 20](https://github.com/user-attachments/assets/69dab4d6-7383-453b-b0b9-5eadf619e7bd)

2024-09-10 15:17 UTC, Jarvv commented on src/services/Models.service.tsx
> +              }}
Add the mesh as a child to the <group>, but reparent the nodes object3D to the object3D of its parent node

2024-09-10 17:10 UTC, ericjansenrpm commented
Looks great James! Please also test the lighting with wings and other attachments. :) For the updated tonemapping try how it looks like with the optional bloom postprocessing that we provide. You can find examples in the storybook.

2024-09-10 19:42 UTC, ericjansenrpm commented on src/components/Lights/Lights.component.tsx
>      fillLightIntensity: 3.0,
let also try to reduce the orange light - we got some feedback there

2024-09-12 09:49 UTC, ericjansenrpm requested changes
Let's create the rc together manually after the storybook was updated. :)

2024-09-12 14:46 UTC, ericjansenrpm approved these changes

2024-09-13 11:00 UTC, Jarvv commented
Tone-mapping fix validated inside local nova-editor

![Screenshot 2024-09-13 at 11 58 39](https://github.com/user-attachments/assets/70e3a111-95b4-433d-ba8c-f2d65cd9fb6b)

2024-09-13 11:03 UTC, merged